### PR TITLE
Login with email if account differs

### PR DESCRIPTION
**Pull request by yvlasenko**
I'm not sure if I'm missing something but current code seems to be expecting account name to be the first part of an email. Adding another field for those unlucky whos account name differs from email.

### CODE REVIEW

**Review by alfficcadenti — COMMENTED** [review]
the code doesn't assume that the username is the frst part of the email. in some part it remove what is after a @ yes, just to prevent email to be used.
But in multiple part of the code, the username is needed to call splinterlands api to get collection card or quest for example. if username is not used, the bot will only use the basic card. So I aim to enforce everyone to use username instead of email address

**Comment by yvlasenko** [comment]
I guess this might be specific to users registered after certain date. This is the message I get when trying to log in with a username: 
Screenshot 2021-08-27 at 20 14 52

**Comment by alfficcadenti** [comment]
because the username requires the posting key and not the password.
If you created the hive account with splinterlands, you need to request keys from the top right menu.
with username and posting key everything will work as expected

**Comment by yvlasenko** [comment]
🤦 how did I miss that? Thank you!

**Pull request closed without merging**
